### PR TITLE
Make tertestrial build before testing

### PR DESCRIPTION
**Pull request by alexdavid**
@kevgo

### CODE REVIEW

**Comment by kevgo** [comment]
Doesn't this make the tests slower? What about running `watch` in the background? Is this how you are normally developing?

**Comment by alexdavid** [comment]
By running watch I feel like that's opening up a race condition where tertestrial could potentially run the tests before compiling.

The compile time seems unnoticeable for me

**Comment by kevgo** [comment]
Hmm, this is true...

**Comment by kevgo** [comment]
Okay, let's try this out here!  🚢

**Pull request merged**
